/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dijkstra.DijkstraAlgo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import trainalgo.stations.Dataset;

/**
 *
 * @author Hishara
 */
public class ClosestRoutes extends javax.swing.JFrame {

    int selectedTextIndex = 0;
    Dataset ds;
    DefaultListModel<String> defaultListModel;
    private static Map<Integer, String> stationDataTreeMap;
    private int[][] stationPaths;
    private DijkstraAlgo dijkstraAlgo;
    private ArrayList<String> shortestPath;
    private String path;
    /**
     * Creates new form ClosestRoutes
     */
    public ClosestRoutes() {
        initComponents();
        initStationDataStruct();
    }
    
    private void initStationDataStruct(){
        System.out.println("Initializing Data Structures");
        ds = new Dataset();
        try{
            ds.initStationPathDatastruct();
            stationPaths = ds.getStationPaths();
            if (stationPaths == null && stationPaths.length == 0) {
                JOptionPane.showMessageDialog(this, "Data set is empty", "Exception", JOptionPane.WARNING_MESSAGE);
                return;
            }
            txtExecutionTime.setText(String.valueOf(ds.getExecutionTime()));
            ds.initStationInfoDatastruct();
            stationDataTreeMap = ds.getStationDataTreeMap();
            defaultListModel = new DefaultListModel<>();
            lstStationNames.setModel(defaultListModel);
            for (Map.Entry<Integer, String> entry : stationDataTreeMap.entrySet()) {
                defaultListModel.addElement(entry.getValue());
            }
            dijkstraAlgo = new DijkstraAlgo(stationPaths, stationDataTreeMap);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "SQL Error : " + e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error : " + e.getMessage(), "Exception", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel53 = new javax.swing.JPanel();
        txtStationB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStationA = new javax.swing.JTextField();
        btnFindPaths = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        btnClose26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtClosestPath = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtExecutionTime = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstStationNames = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel53.setBackground(new java.awt.Color(255, 255, 255));
        jPanel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));

        txtStationB.setEditable(false);
        txtStationB.setBackground(new java.awt.Color(255, 255, 255));
        txtStationB.setForeground(new java.awt.Color(102, 102, 102));
        txtStationB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStationBMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Station A");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Station B");

        txtStationA.setEditable(false);
        txtStationA.setBackground(new java.awt.Color(255, 255, 255));
        txtStationA.setForeground(new java.awt.Color(102, 102, 102));
        txtStationA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStationAMouseClicked(evt);
            }
        });

        btnFindPaths.setBackground(new java.awt.Color(102, 153, 255));
        btnFindPaths.setForeground(new java.awt.Color(255, 255, 255));
        btnFindPaths.setText("Find Paths");
        btnFindPaths.setBorder(null);
        btnFindPaths.setBorderPainted(false);
        btnFindPaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPathsActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Railway Stations");

        jPanel55.setBackground(new java.awt.Color(102, 153, 255));

        jPanel54.setBackground(new java.awt.Color(255, 102, 102));
        jPanel54.setPreferredSize(new java.awt.Dimension(25, 25));

        btnClose26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClose26.setForeground(new java.awt.Color(0, 0, 0));
        btnClose26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose26.setText("X");
        btnClose26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose26MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose26, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addComponent(btnClose26)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Find Routes");

        javax.swing.GroupLayout jPanel55Layout = new javax.swing.GroupLayout(jPanel55);
        jPanel55.setLayout(jPanel55Layout);
        jPanel55Layout.setHorizontalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel55Layout.setVerticalGroup(
            jPanel55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel55Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
            .addGroup(jPanel55Layout.createSequentialGroup()
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtClosestPath.setColumns(20);
        txtClosestPath.setRows(5);
        jScrollPane3.setViewportView(txtClosestPath);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Closest Route Information");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Execution Time (nanoseconds)");

        txtExecutionTime.setForeground(new java.awt.Color(102, 102, 102));
        txtExecutionTime.setText("0000000");

        lstStationNames.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstStationNamesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstStationNames);

        javax.swing.GroupLayout jPanel53Layout = new javax.swing.GroupLayout(jPanel53);
        jPanel53.setLayout(jPanel53Layout);
        jPanel53Layout.setHorizontalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel53Layout.createSequentialGroup()
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel53Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel53Layout.createSequentialGroup()
                                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel53Layout.createSequentialGroup()
                                        .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(txtExecutionTime))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel53Layout.createSequentialGroup()
                                        .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStationB)
                                            .addGroup(jPanel53Layout.createSequentialGroup()
                                                .addComponent(txtStationA, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(btnFindPaths, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(76, 76, 76)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel53Layout.setVerticalGroup(
            jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel53Layout.createSequentialGroup()
                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtStationA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel53Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtStationB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnFindPaths, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExecutionTime)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel53Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(765, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClose26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose26MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnClose26MouseClicked

    private void txtStationAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStationAMouseClicked
        // TODO add your handling code here:
        txtStationA.setText("Select Station from Station Names");
        selectedTextIndex = 0;
    }//GEN-LAST:event_txtStationAMouseClicked

    private void txtStationBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStationBMouseClicked
        // TODO add your handling code here:
        txtStationB.setText("Select Station from Station Names");
        selectedTextIndex = 1;
    }//GEN-LAST:event_txtStationBMouseClicked

    private void lstStationNamesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstStationNamesMouseClicked
        // TODO add your handling code here:
        if (selectedTextIndex == 0)
            txtStationA.setText(lstStationNames.getSelectedValue());
        else
            txtStationB.setText(lstStationNames.getSelectedValue());
    }//GEN-LAST:event_lstStationNamesMouseClicked

    private void btnFindPathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPathsActionPerformed
        // TODO add your handling code here:
        if (txtStationA.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a Station from the List to Station A", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txtStationB.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please select a Station from the List to Station B", "Input Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(dijkstraAlgo!=null){
            dijkstraAlgo.applyDijkstra(ds.retrieveStationID(txtStationA.getText()));
            shortestPath = dijkstraAlgo.getShortestPath(ds.retrieveStationID(txtStationB.getText()));
            
            if(shortestPath.isEmpty()){
                JOptionPane.showMessageDialog(this, "Couldn't generate path", "Path Error", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            path = "";
            shortestPath.forEach((p) -> {
                path = path + p + " -> ";
            });
            txtClosestPath.setText(path);
            txtClosestPath.append("\n==DISTANCE : " + dijkstraAlgo.getDistance());
            txtExecutionTime.setText(String.valueOf(dijkstraAlgo.getExecutedTime()));
        }
    }//GEN-LAST:event_btnFindPathsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClosestRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClosestRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClosestRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClosestRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClosestRoutes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose26;
    private javax.swing.JButton btnFindPaths;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstStationNames;
    private javax.swing.JTextArea txtClosestPath;
    private javax.swing.JLabel txtExecutionTime;
    private javax.swing.JTextField txtStationA;
    private javax.swing.JTextField txtStationB;
    // End of variables declaration//GEN-END:variables
}
